// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2J35hDRKVjN_fEqqhxVix1wvYoy1bSzQ',
    appId: '1:825561479353:web:11df80a0781ad0b7f0c368',
    messagingSenderId: '825561479353',
    projectId: 'assignment-c9b91',
    authDomain: 'assignment-c9b91.firebaseapp.com',
    storageBucket: 'assignment-c9b91.appspot.com',
    measurementId: 'G-RB9N0CMY2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpD4Slm_Z3Ji16iiPTHUKku7lQ1aU8N3U',
    appId: '1:825561479353:android:eeaf68566bf05d18f0c368',
    messagingSenderId: '825561479353',
    projectId: 'assignment-c9b91',
    storageBucket: 'assignment-c9b91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApZ4OluOm4zBGffB6OnS8REDYnanuBHDE',
    appId: '1:825561479353:ios:b5029f91a590adaff0c368',
    messagingSenderId: '825561479353',
    projectId: 'assignment-c9b91',
    storageBucket: 'assignment-c9b91.appspot.com',
    iosBundleId: 'com.example.eCommerceAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApZ4OluOm4zBGffB6OnS8REDYnanuBHDE',
    appId: '1:825561479353:ios:b5029f91a590adaff0c368',
    messagingSenderId: '825561479353',
    projectId: 'assignment-c9b91',
    storageBucket: 'assignment-c9b91.appspot.com',
    iosBundleId: 'com.example.eCommerceAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2J35hDRKVjN_fEqqhxVix1wvYoy1bSzQ',
    appId: '1:825561479353:web:6c2db6497be70a9df0c368',
    messagingSenderId: '825561479353',
    projectId: 'assignment-c9b91',
    authDomain: 'assignment-c9b91.firebaseapp.com',
    storageBucket: 'assignment-c9b91.appspot.com',
    measurementId: 'G-84991VCWVL',
  );
}
